export const translations = {
  pt: {
    inputNamePlaceholder: "Digite seu nome...",
    start: "Iniciar",
    welcome: "Bem-vindo (a)",
    modeComputingTitle: "Mulheres na Computação",
    modeComputingDesc: "Conheça as mentes brilhantes que moldaram a história da tecnologia.",
    modeMathTitle: "Mulheres na Matemática",
    modeMathDesc: "Descubra as mentes geniais que decifraram os mysteries do universo através dos números.",
    modeChemistryTitle: "Mulheres na Química",
    modeChemistryDesc: "Das reações em laboratório à tabela periódica: as cientistas que manipularam a matéria para criar o mundo moderno.",
    modeBiologyTitle: "Mulheres na Biologia",
    modeBiologyDesc: "Seja no microscópio ou no coração da floresta, estas mulheres redefiniram nossa compreensão sobre a vida e a evolução.",
    modePhilosophyTitle: "Mulheres na Filosofia e Lógica",
    modePhilosophyDesc: "Do questionamento da existência às equações de lógica pura: as mentes que reescreveram as estruturas do pensamento.",
    modePsychologyTitle: "Mulheres na Psicologia",
    modePsychologyDesc: "Dos mistérios do inconsciente à ciência do comportamento: as pioneiras que mapearam os labirintos da mente humana.",
    statsPoints: "Pontos",
    statsMatches: "Acertos",
    statsTries: "Tentativas",
    statsAccuracy: "Precisão",
    rankingTitle: "Classificação",
    rankingPointsTab: "Pontos",
    rankingAccuracyTab: "Precisão",
    selectDifficulty: "Selecione a Dificuldade",
    difficultyDescription: "Isso afetará o algoritmo e a quantia de cartas:",
    diffEasyName: "Aprendiz",
    qtyCards10: "10 Cartas",
    diffMediumName: "Pesquisador",
    qtyCards15: "15 Cartas",
    diffHardName: "Doutor / PhD", // 🎓 Atualizado para Doutor
    qtyCards20: "20 Cartas"
  },
  en: {
    inputNamePlaceholder: "Type your name...",
    start: "Start",
    welcome: "Welcome",
    modeComputingTitle: "Women in Computing",
    modeComputingDesc: "Meet the brilliant minds who shaped the history of technology.",
    modeMathTitle: "Women in Mathematics",
    modeMathDesc: "Discover the genius minds who unlocked the mysteries of the universe through numbers.",
    modeChemistryTitle: "Women in Chemistry",
    modeChemistryDesc: "From laboratory reactions to the periodic table: the scientists who manipulated matter to create the modern world.",
    modeBiologyTitle: "Women in Biology",
    modeBiologyDesc: "Whether under the microscope or in the heart of the forest, these women redefined our understanding of life and evolution.",
    modePhilosophyTitle: "Women in Philosophy and Logic",
    modePhilosophyDesc: "From questioning existence to pure logic equations: the minds that rewrote the structures of thought.",
    modePsychologyTitle: "Women in Psychology",
    modePsychologyDesc: "From the mysteries of the unconscious to behavioral science: the pioneers who mapped the labyrinths of the human mind.",
    statsPoints: "Points",
    statsMatches: "Match Attempts",
    statsTries: "Tries",
    statsAccuracy: "Accuracy",
    rankingTitle: "Ranking",
    rankingPointsTab: "Points",
    rankingAccuracyTab: "Accuracy",
    selectDifficulty: "Select Difficulty",
    difficultyDescription: "This will affect the algorithm and the amount of cards:",
    diffEasyName: "Apprentice",
    qtyCards10: "10 Cards",
    diffMediumName: "Researcher",
    qtyCards15: "15 Cards",
    diffHardName: "Doctor / PhD", // 🎓 Atualizado para Doutor
    qtyCards20: "20 Cards"
  },
  es: {
    inputNamePlaceholder: "Escribe tu nombre...",
    start: "Iniciar",
    welcome: "Bienvenido (a)",
    modeComputingTitle: "Mujeres en la Computación",
    modeComputingDesc: "Conoce a las mentes brillantes que dieron forma a la historia de la tecnología.",
    modeMathTitle: "Mujeres en las Matemáticas",
    modeMathDesc: "Descubre a las mentes geniales que descifraron los misterios del universo a través de los números.",
    modeChemistryTitle: "Mujeres en la Química",
    modeChemistryDesc: "De las reacciones de laboratorio a la tabla periódica: las científicas que manipularon la materia para crear el mundo moderno.",
    modeBiologyTitle: "Mujeres en la Biología",
    modeBiologyDesc: "Ya sea bajo el microscopio o en el corazón da la selva, estas mujeres redefinieron nuestra comprensión de la vida y la evolución.",
    modePhilosophyTitle: "Mujeres en la Filosofía y Lógica",
    modePhilosophyDesc: "Desde el cuestionamiento de la existencia hasta las ecuaciones de lógica pura: las mentes que reescribieron las estructuras del pensamento.",
    modePsychologyTitle: "Mujeres en la Psicología",
    modePsychologyDesc: "De los misterios del inconsciente a la ciencia del comportamiento: las pioneiras que mapearon los laberintos de la mente humana.",
    statsPoints: "Puntos",
    statsMatches: "Coincidencias",
    statsTries: "Intentos",
    statsAccuracy: "Precisión",
    rankingTitle: "Clasificación",
    rankingPointsTab: "Puntos",
    rankingAccuracyTab: "Precisión",
    selectDifficulty: "Seleccionar Dificultad",
    difficultyDescription: "Esto afectará el algoritmo y la cantidad de cartas:",
    diffEasyName: "Aprendiz",
    qtyCards10: "10 Cartas",
    diffMediumName: "Investigador",
    qtyCards15: "15 Cartas",
    diffHardName: "Doctor / PhD", // 🎓 Atualizado para Doutor
    qtyCards20: "20 Cartas"
  }
};
